require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe RsvpsController do

  def mock_rsvp(stubs={})
    @mock_rsvp ||= mock_model(Rsvp, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all rsvps as @rsvps" do
      Rsvp.stub(:all) { [mock_rsvp] }
      get :index
      assigns(:rsvps).should eq([mock_rsvp])
    end
  end

  describe "GET show" do
    it "assigns the requested rsvp as @rsvp" do
      Rsvp.stub(:find).with("37") { mock_rsvp }
      get :show, :id => "37"
      assigns(:rsvp).should be(mock_rsvp)
    end
  end

  describe "GET new" do
    it "assigns a new rsvp as @rsvp" do
      Rsvp.stub(:new) { mock_rsvp }
      get :new
      assigns(:rsvp).should be(mock_rsvp)
    end
  end

  describe "GET edit" do
    it "assigns the requested rsvp as @rsvp" do
      Rsvp.stub(:find).with("37") { mock_rsvp }
      get :edit, :id => "37"
      assigns(:rsvp).should be(mock_rsvp)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created rsvp as @rsvp" do
        Rsvp.stub(:new).with({'these' => 'params'}) { mock_rsvp(:save => true) }
        post :create, :rsvp => {'these' => 'params'}
        assigns(:rsvp).should be(mock_rsvp)
      end

      it "redirects to the created rsvp" do
        Rsvp.stub(:new) { mock_rsvp(:save => true) }
        post :create, :rsvp => {}
        response.should redirect_to(rsvp_url(mock_rsvp))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rsvp as @rsvp" do
        Rsvp.stub(:new).with({'these' => 'params'}) { mock_rsvp(:save => false) }
        post :create, :rsvp => {'these' => 'params'}
        assigns(:rsvp).should be(mock_rsvp)
      end

      it "re-renders the 'new' template" do
        Rsvp.stub(:new) { mock_rsvp(:save => false) }
        post :create, :rsvp => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested rsvp" do
        Rsvp.stub(:find).with("37") { mock_rsvp }
        mock_rsvp.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :rsvp => {'these' => 'params'}
      end

      it "assigns the requested rsvp as @rsvp" do
        Rsvp.stub(:find) { mock_rsvp(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:rsvp).should be(mock_rsvp)
      end

      it "redirects to the rsvp" do
        Rsvp.stub(:find) { mock_rsvp(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(rsvp_url(mock_rsvp))
      end
    end

    describe "with invalid params" do
      it "assigns the rsvp as @rsvp" do
        Rsvp.stub(:find) { mock_rsvp(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:rsvp).should be(mock_rsvp)
      end

      it "re-renders the 'edit' template" do
        Rsvp.stub(:find) { mock_rsvp(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rsvp" do
      Rsvp.stub(:find).with("37") { mock_rsvp }
      mock_rsvp.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the rsvps list" do
      Rsvp.stub(:find) { mock_rsvp }
      delete :destroy, :id => "1"
      response.should redirect_to(rsvps_url)
    end
  end

end
